CREATE TABLE ADMINS (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    PRIMARY KEY (admin_id)
);

CREATE TABLE STAFF (
    staff_id NUMBER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(255),
    mobile_number VARCHAR2(20),
    address VARCHAR2(255),
    nid VARCHAR2(20),
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    PRIMARY KEY (staff_id)
);

CREATE TABLE CUSTOMERS (
    customer_id NUMBER GENERATED ALWAYS AS IDENTITY,
    name VARCHAR2(255),
    email VARCHAR2(255),
    phone VARCHAR2(20),
    PRIMARY KEY (customer_id)
);

CREATE TABLE STOCK (
    item_code VARCHAR2(50) PRIMARY KEY,
    category VARCHAR2(255),
    item_name VARCHAR2(255),
    price NUMBER,
    discount NUMBER,
    quantity NUMBER,
    image VARCHAR2(255),
    expiry_date DATE
);

CREATE TABLE ORDERS (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE,
    customer_id NUMBER,
    item_code VARCHAR2(50),
    quantity NUMBER,
    total_price NUMBER,
    discount NUMBER,
    final_price NUMBER,
    PRIMARY KEY (order_id),
    FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),
    FOREIGN KEY (item_code) REFERENCES STOCK(item_code)
);

CREATE TABLE CONTACT_MESSAGES (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    phone_number VARCHAR2(20) NOT NULL,
    subject VARCHAR2(255) NOT NULL,
    message CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (message_id)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER,
    item_code VARCHAR2(50),
    quantity NUMBER,
    price NUMBER,
    PRIMARY KEY(order_item_id),
    FOREIGN KEY(order_id) REFERENCES orders(order_id)
);
